FROM alpine:3.18.0

RUN apk update
RUN apk upgrade
RUN apk add bash
RUN apk add alpine-sdk
RUN apk add dotnet7-sdk

######################### Download and build spot #########################
WORKDIR /home
RUN wget https://www.lrde.epita.fr/dload/spot/spot-2.11.5.tar.gz
RUN tar -xf spot-2.11.5.tar.gz
WORKDIR /home/spot-2.11.5

RUN ./configure --disable-python 
RUN make 
##################################################

######################### Copy and build CATS #########################
COPY src /home/src

WORKDIR /home/src/CATS
RUN dotnet build -c "release" -o ../../app

# Copy paths.json which points to local path of spot within the container
COPY docker/paths.json /home/app/paths.json
##################################################

WORKDIR /home

VOLUME ["/home/examples"]

ENTRYPOINT ["/home/app/CATS"]
